# Generated by Django 6.0 on 2026-01-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto_url', models.URLField(verbose_name='URL de la Foto')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('calendario_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.TextField()),
                ('imagen_url', models.URLField(verbose_name='URL de la Imagen')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('siglas', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('logo_url', models.URLField(verbose_name='URL del Logo')),
                ('web_oficial', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo_url', models.URLField(verbose_name='URL del Logo')),
                ('red_social', models.URLField()),
                ('sede', models.CharField(default='CDMX', max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='api.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='api.organizacion'),
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apodo', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_url', models.URLField(blank=True, null=True, verbose_name='URL Foto Piloto')),
                ('red_social', models.URLField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilotos', to='api.equipo')),
            ],
        ),
    ]
