# Generated by Django 6.0 on 2026-01-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='¿Serie Activa?'),
        ),
    ]
