# Generated by Django 6.0 on 2026-01-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria_activa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piloto',
            old_name='red_social',
            new_name='instagram',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='red_social',
        ),
        migrations.AddField(
            model_name='equipo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='web_oficial',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web Equipo'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='web_oficial',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
    ]
