# Generated by Django 6.0 on 2026-01-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_red_social_piloto_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='web_oficial',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web Oficial'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='web_oficial',
            field=models.URLField(blank=True, null=True),
        ),
    ]
