# Generated by Django 6.0 on 2026-01-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_categoria_facebook_categoria_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='sede',
        ),
    ]
