# Generated by Django 6.0 on 2026-01-04 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_equipo_logo_url_remove_equipo_sede'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='api.categoria'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(default='Texto pendiente', verbose_name='Contenido Completo de la Noticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='api.equipo'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='api.organizacion'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_url',
            field=models.URLField(verbose_name='URL de la Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(help_text='Texto corto para la tarjeta de previsualización'),
        ),
    ]
