# Generated by Django 6.0 on 2026-01-04 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='cuerpo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(default='pendiente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='link_resultado',
            field=models.URLField(blank=True, help_text='Poner aquí el link al PDF o tabla de tiempos (solo para Resultados)', null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tipo',
            field=models.CharField(choices=[('NOTICIA', 'Noticia General'), ('RESULTADO', 'Resultado de Carrera')], default='NOTICIA', max_length=20),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='organizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organizacion'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(),
        ),
    ]
