# Generated by Django 6.0 on 2026-01-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_noticia_cuerpo_noticia_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
