# Generated by Django 6.0 on 2026-01-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_noticia_contenido_alter_noticia_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='resumen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
