# Generated by Django 6.0 on 2026-01-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_noticia_resumen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='fecha_manual',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Manual (Opcional)'),
        ),
    ]
