# Generated by Django 6.0 on 2026-01-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_noticia_fecha_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='equipo_administrado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrador', to='api.equipo'),
        ),
    ]
