# Generated by Django 6.0 on 2026-01-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_perfilusuario_equipo_administrado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='facebook',
            new_name='logo_url',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='instagram',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
