# Generated by Django 6.0 on 2026-01-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_facebook_equipo_logo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloto',
            name='nacionalidad',
            field=models.CharField(default='INT', max_length=50),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='piloto',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
