# Generated by Django 6.0 on 2026-01-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_piloto_nacionalidad_alter_piloto_foto_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
